name: "CI"

on:
    push:
        branches:
            - 'main'
        paths-ignore:
            - "**.md"
    pull_request:
        paths-ignore:
            - "**.md"

jobs:
    lint:
        runs-on: "ubuntu-latest"
        name: "Linting"
        steps:
            -   name: 'Checkout'
                uses: 'actions/checkout@v3'

            -   name: "Install PHP"
                uses: 'shivammathur/setup-php@v2'
                with:
                    php-version: '8.2'
                    tools: 'composer:v2'

            -   name: 'Install Dependencies'
                run: 'composer install --no-interaction --no-progress --no-suggest'

            -   name: 'ESC'
                run: 'vendor/bin/ecs'

            -   name: 'PHPStan'
                run: 'vendor/bin/phpstan'

    test:
        runs-on: "ubuntu-latest"
        strategy:
            max-parallel: 16
            fail-fast: false
            matrix:
                php-version:
                    - '8.0'
                    - '8.1'
                    - '8.2'

        name: "Testing against PHP ${{ matrix.php-version }}"
        steps:
            -   name: 'Checkout'
                uses: 'actions/checkout@v3'

            -   name: "Install PHP"
                uses: 'shivammathur/setup-php@v2'
                with:
                    php-version: '${{ matrix.php-version }}'
                    tools: 'composer:v2'

            -   name: 'Install Dependencies'
                run: 'composer install --no-interaction --no-progress --no-suggest'

            -   name: 'PHPUnit'
                run: 'vendor/bin/phpunit'
